apiVersion: v1
data:
  eslint-no-dev-errors: dHJ1ZQ==
  react-app-api-url: aHR0cDovL2xvY2FsaG9zdC9hcGk=
  react-app-assets-bucket: aHR0cHM6Ly9saWdodGVuY2UtYXNzZXRzLnMzLmFtYXpvbmF3cy5jb20=
  react-app-base-url: aHR0cDovL2xvY2FsaG9zdC8=
  react-app-be: bG9jYWxob3N0
  react-app-device-command-token: ZDFmNDllMTYtNmM3My00NGM5LTgzNzktMjVkYjkyYWI3ZjNm
  react-app-mqtt-connection: d3NzOi8vNTdhNmNjMWUzY2ZlNDRhYWE1NDQ5YmIxNzQ0OGQwNzguczEuZXUuaGl2ZW1xLmNsb3VkOjg4ODQvbXF0dA==
  react-app-mqtt-password: S2hvbmdjaG8x
  react-app-mqtt-user: YWRtaW4=
  tsc-compile-on-error: dHJ1ZQ==
kind: Secret
metadata:
  name: uiapp-secret
type: Opaque