apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    name: user-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api
        image: harbor.securityzone.kh:8030/demo/user-service:122
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: env-file
              readOnly: true
              mountPath: "/app/.env"
              subPath: .env
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: userdb-secret
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  key: port
                  name: userdb-secret
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: env-file
          secret:
            secretName: fastapi-userdb-cred
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWcudWl0aW90LnZuIjogewoJCQkiYXV0aCI6ICJNakUxTWpJeE5URTZTMmh2Ym1kamFHOHgiCgkJfSwKCQkicmVnaXN0cnktaGFyYm9yLm5nb2RhdDAxMDMubWUiOiB7CgkJCSJhdXRoIjogImEyaGhZMmgxZVRwTVJ5Y2lNVGt5SVdKMlBsMURmajV3IgoJCX0KCX0KfQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-userdb-cred
  namespace: default
stringData:
  .env: |
    DATABASE_URL=postgresql://admin:Khongcho1@userdb-svc:5432/
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    service: user-svc
spec:
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 8002
      targetPort: 8000
      protocol: TCP
  selector:
    app: user-api
