apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdb-pv
  namespace: database
  labels:
    type: local
spec:
  storageClassName: mannual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"